classDiagram
    class ConcreteMethodType
    ConcreteMethodType : Action Action
    ConcreteMethodType : Class Class
    ConcreteMethodType o-- MethodType
    class MethodPart
    MethodPart : Action Action
    MethodPart : Composite Composite
    MethodPart : Domain Domain
    class MethodType
    MethodType o-- MethodPart
    MethodType : String Name
